### ISSUE TITLE
rewrite

### ISSUE THREAD

**Issue by sunnysideup** [sunnysideup/silverstripe-share_this_simple#2]
- create an interface for a social media platform (SMP)
- allow devs to register social media platforms (FB + TW by default)
- each SMP has its own class implementing the Interface

private static setting

```yml
ShareThisSimpleProvider:
  use:
    - Sunnysideup\ShareThisSimple\Platforms\Facebook
    - Sunnysideup\ShareThisSimple\Platforms\Twitter
    - etc...
```
